---
- project:
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-kubernetes-power-manager-tox-py39
        - k8sapp-kubernetes-power-manager-tox-flake8
        - k8sapp-kubernetes-power-manager-tox-pylint
        - k8sapp-kubernetes-power-manager-tox-bandit
        - k8sapp-kubernetes-power-manager-tox-metadata
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-kubernetes-power-manager-tox-py39
        - k8sapp-kubernetes-power-manager-tox-flake8
        - k8sapp-kubernetes-power-manager-tox-pylint
        - k8sapp-kubernetes-power-manager-tox-bandit
        - k8sapp-kubernetes-power-manager-tox-metadata
    post:
      jobs:
        - stx-app-kubernetes-power-manager-upload-git-mirror

- job:
    name: k8sapp-kubernetes-power-manager-tox-py39
    parent: tox-py39
    description: |
        Run py39 for kubernetes-power-manager
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-kubernetes-power-manager/*
    vars:
        tox_envlist: py39
        tox_extra_args: -c python3-k8sapp-kubernetes-power-manager/k8sapp_kubernetes_power_manager/tox.ini
        tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-kubernetes-power-manager-tox-flake8
    parent: tox
    description: |
        Run flake8 for kubernetes-power-manager
    nodeset: debian-bullseye
    files:
      - python3-k8sapp-kubernetes-power-manager/*
    vars:
        tox_envlist: flake8
        tox_extra_args: -c python3-k8sapp-kubernetes-power-manager/k8sapp_kubernetes_power_manager/tox.ini

- job:
    name: k8sapp-kubernetes-power-manager-tox-metadata
    parent: tox
    description: |
        Run metadata test for kubernetes-power-manager
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    vars:
        tox_envlist: metadata
        tox_extra_args: -c python3-k8sapp-kubernetes-power-manager/k8sapp_kubernetes_power_manager/tox.ini
        tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-kubernetes-power-manager-tox-pylint
    parent: tox
    description: |
        Run pylint test for kubernetes-power-manager
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-kubernetes-power-manager/*
    vars:
        tox_envlist: pylint
        tox_extra_args: -c python3-k8sapp-kubernetes-power-manager/k8sapp_kubernetes_power_manager/tox.ini
        tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-kubernetes-power-manager-tox-bandit
    parent: tox
    description: |
      Run bandit test for kubernetes-power-manager
    nodeset: debian-bullseye
    files:
      - python3-k8sapp-kubernetes-power-manager/*
    vars:
      tox_envlist: bandit
      tox_extra_args: -c python3-k8sapp-kubernetes-power-manager/k8sapp_kubernetes_power_manager/tox.ini

- job:
    name: stx-app-kubernetes-power-manager-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/app-kubernetes-power-manager to
      github.com/starlingx/app-kubernetes-power-manager
    vars:
      git_mirror_repository: starlingx/app-kubernetes-power-manager
    secrets:
      - name: git_mirror_credentials
        secret: stx-app-kubernetes-power-manager-github-secret2
        pass-to-parent: true

- secret:
    name: stx-app-kubernetes-power-manager-github-secret2
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - Mj5gAmUNcSXlozAhgRkxkNBplr3ORuKOWFIf6ymObgwdk91qOJltB750KEouDXDzJLbAY
          Xv9/EyHUptOAMbRb2EHmADAn8ESf5bR6w5enRFCBy5l8U28wc3D82dX9eC6a/vHNVyaGd
          XpDVy3H5C0hhtw2fm5J5PN/0ChJH8N8ZuJoZXNvY5Xcxc9m7oR32CZPX4NkbKZcxdFl4c
          q2r0eIs9Tuiw1PL28aBBk+bsli4Qb582dnYSTIUPF54bMG94y4rJwpn8jWd6HWslLPPFO
          w+iyd6RuEBd3xtYMNgJByLSiJVqEu1EEmlizHiT09BlXqMh1/lLH+LiLC8Wp+vFH4ZQ9+
          6DOqGKZ6cRvkX79KNUbdHt1ackiX64QZOXB/Irjq1G/NpQUHhmpx05fADOEp3/lxw5Q0z
          Q5JVUhVWDtxjbyg111Q2rtnEzw9iqOu6YNjZ+A6XL0hPksTxFAPzxZ8/h4zJgBmm5Ahmb
          eOUWbPZWuxzy0fseg4UZhlUJrXrw+ZZhji+mb4qU+KGjzrLHT+bcqz5Egc0K3IsHR0Pv4
          +JyHtUx9GldiafHioeKcIaKuTSWuDC7ZaWLyXZWhrkNDaiZOVYZTAAgP6SnAGEqQwCw/G
          xgvvayF1oN2pHbXKeNm/9iwUfq9HAcjhZ6HgzMBATEr6SNO5UWi5gywJIrDR5w=
        - gUxKb5XCZ3tdAfD2ZN78E/CFihHRYd2dsQ3dUwkNmRmi8WEZdUzwL1WlF+/6ZZrJtmunV
          23HF7oUb0G9Y8vyfQQEcJuGSJanAYTySDLO3nkuxT1a1/OcTH/Ni2WYymoVs+VbI0f7Sw
          r+r7O9I28/xI4CKywAWXr4gseQJdYbGVYvzX65foJ8tE4gp3TyUl32k4n2+Elq3NNuJQk
          lJlOAZHlxNhjLppwK+xl7j8pnjskrDhXeMGeqh1WtcsYq73D2A0VgZ8SnHbiwCHRF4fMl
          zV6zEi4p2nZKAiwupzERIJWW+tSNXeKf2Qedt46RR5wI6K3oHI5qNpHckycPJDilGgGNm
          eXF9g00tcRkTuBH5xu3a4EkNb3yLAhZ+U8Er6wiWtN62Ned4VfVokM7gfgGfgx6DCDDUi
          1aOrS00QWALUEnJz8a99n9UcC3d7v0mDFOofrNqA47W6bx1AW6Yv31Pmzd8TjPvXK4t9q
          ANMahcU/K0bPqIbevEt34xUaFAc0HeM9QZxIa1tvRDKv5TLs/tyH8FKDdwyt62hW9EMvH
          3oabDanxeMKWAchNBtknld1lj8gjHiLtNCuHZa4EKlN0TlZsWPVTVmUsETffVculojVpk
          Ss2Q+w1xAj/kmz5oWuLvBCwrHQzq8FtrlG5iDBQJXPTs35TwTyBJaFy3UDLmno=
        - HthRo7K5u13LPVDNzuRu7XQ7ZyC4dN/sQ0TXitC4Isgmm/F6v09qTV0oz7OvTYtmTgQxZ
          Mt/5UaZMOs2R/N7AicCwRAmfQbwv1cJn3Bf6N2WCU88E5Q+KExG8OFOh8xDzIgCk3MkEx
          BdkX3RzmjBKG5tf43yxBOnPRVoEbw3pYriZ8HpIY2e5E5P2st5gXloxkBzwdYRzUUb4OY
          YuU8ruDhCvFVBehojBmJqIbJgnw2ZJW+DW9tpdnMVgdLUgM2ppekuKHJsy/rDwsFXi18M
          f7y+3kkF7ibMOCA8QTtNZSdD1r0m6lN+MiRs2n6iKej3JRsqbL+3dTjBqED21qaKANSuo
          eatxYiSlP4NzaxqeHpbp3xbLFKJqO7jjYnarWSK8xCjnqvI/Qtu5XRqFPZCcjjsij1ZtB
          zmQ1hRzuqZvDSxaVROU+iB5EFJr1ag0wuATBauj1DYzoH1mj3d3NZMuy1nQdY5RFw/oqt
          V2xFkENpMYsOPSfAuPCJVJGZbVAo8cNAVdeAV361MWbeL8F/YJo65gKwRhjOXyr6V9DBJ
          6lm/tLr1Jgitk9+jI8sklW5IyAnh5VeYg0uSEvx3ZqaDrMTh38YV4NYw/zVDBDmjiZd7F
          dUWnenZjjlerRAr3HJ/74RPq3GDiDA8YP0KphOFY4S49rSLwjQZHe5FvMZSu5g=
        - RqUZSRxcFrYX+k3bgKe65hJBwKBZsI39kCE7u89+UTWjCI6WB6LtJxSAS0GOh4dBH2UBY
          gG402CRQGjIC2rtIMJ4adlZ8xdqCQfakXWyfqE9i+XM+KDnY3OwIDyAKqTrGCoUsu547e
          9jDFtsw7Xyf1VKBocJuAUwxrkuqQDugWWEfCFxDbFQ7+Je26thMra6B9EDpOlezqKwEju
          ljfK16cUMdBFFYNg62zR3QWVCEf6plW2klJPmwuO7a9EVcymzlWmoKOZYwIZQGntTBWyt
          Igxc80XYmt3QBx5MkVBA6BMy77LqUIRs0RaXSzu9s0kXJBoQbesdNrCmb7m28+yo2tKXS
          M5Uixg/IS9K9n7n9uKi8PszV2JBayrXRtwAFYyf/aMZmYp/lvttVrq+0gN4bvWTnA6Jru
          esTIr/VaubXIPY3CsLGoXJ2QQXCHzbLtuJdaBG3SSNlmZXNHkuNLF8YWFY8KJvVyRvDOY
          1/ytvkCg47AK59FOIA9g75uICJiu8xvPhJN8oOM1a9yap2SrCc0lo54wCbonOtm1yzHYr
          dQ0H/c0Dgh/EP2Ucn+Jeba6kfhFb/4UcjFKUMPXVkukdP6DarysF7z50VNZbxNvrzAHZb
          oSulmXbpzvYJPEpkwnOsgV7TQxhDS3iHB2hTwh5OvPZg4bOb6jt+/8EK4waIWI=
        - U5mq9nSjMulzViFbADmczqE7M0hExMXBeqmZKR+2pPfQJWIJaCGt26uttgD3JvFI4Mu4u
          WC1On3KwRN5sPqj/JUIJsBvihM4rcE+10HH4n+xVRmQ7IvOKpTqmvAs0YcrX4v86HGURQ
          vLOUR2SFQNc6QjhH67MZ5/PLOYK12Lrfa6p9jJws90dCqAnFLKNZF5oOCiWZshUD4lE1h
          hmce2y43jPS9mTMkfzsG4GjShO0/Q5H0vntdr5slzS3e2+uqcIUcP2Nus2KLNge5wKnly
          W/FeaaFyBNpe4ApUoLODwxLZjhOYjGM9jPmAd9B3AVQshPyvz5//5HenfQFOJmfyCJve1
          F8XAiItoO/xa9Ro6VIDhdaTghlMdrc+FhmW+doRBpgND6bDDRUIm/sHvY7CfUeb1KMKVD
          KpXZe6pzrPC7h609e23I6o35EorS7kUovhy5irP7HT7KMkSxOM7uj+2wljCasPjxiIvLt
          TOhjvu/OQzm791hei7EomHU99uqKXnZSzY9lDJCDAcOLcE8tx2x9Vc5lKK5EvalUg1CDr
          WizE6BjmoCjz2KzUt3ZCUhVXmEHkUr3KawMAqxTUAhCIHWqH8WG5yd0586+J6lQNhPvxS
          UrBue6u4z/7RaIofURopB5cxQIUWy3MhUeN/J5yuGBweZVtIjsSR5eNvI5wgsk=
        - DqAzsMKfrzcxDTlr+ZuVAYE9YOYPwXn86esqFki2cbIObt9eh04gHitnz6qvJPSPLg8qi
          Qfvqs5kIaZ5mP5+wDCJvr3nfq9yTwopoui1RAkDgtfAufbtaMDtscao6S5o1fMn6GoSsk
          oDjl7ywmoVr7nKA9Nk6DBq6fEfn5obcoYwXuN1COvoELCvn77iesSn3gpk4lSY5wR8BOI
          xrnQxiCr+Tx+URJJOHNi0zA2zyX6HCpTYWxPpfAfrwW7aWj8adjMHAiW6EF5lc7nqwZtx
          E7j/YTrF3Vc29x/n7zxxNfoEkIEjB3XVe13WL9Ws1bQDXVvDCTFzW+10I6meZDmf6/x9U
          AkTdzafMY5eTOCm3kPnA/zDIM+zjnwh/eJ6MqiggUh6rBxFsmwteYJZLD861VHX9uoanm
          /U+/0g9S4KQHz5s6PAdRQUZVsxXHBaQjfYQG2i/Nb0RfNKAZ1QBW5ic+lOBR7KC/qUCn6
          luPk0qzsLRwchzeVHpnQJZ1+kgiMzh8ek3Ulc7XEmAiAAEeehOYPhsYMV/iLGxcvy9whw
          xBtVsYJc6MHmeh6VsNriwc32WscB2hFRxBg6Jhgt+vgcJs/3723Tw+k3ndS5wVlY/phEl
          gOrKGVSp+s1SpotIEpOCUcXlgTaDdkhSMtQQQE9F/TU4HybqFhQ3j31jY2ETKg=
        - MznMCEp6EDMxGUHI8GRL/CjBrLyvaN74r7kMI3EuG5+W7paZQfhK0eZ8d6FF5IwlxhKZ/
          dAhgEvvpX0KcQqBdVAWL53NOL8Uy9yOCVa6nEgnlQE3hzVTF0HDy1F4mx3dQ4/UrThsPu
          jHzbQMTTwk/MtLeo9uHhsRgLVoNVkFJ4zww0WsEGZMqeTeaEofWyV7gUQAfhfbU+sprhn
          4IUXFhso/NvADVpUTeshL4Mf6E2tR9cH7MwV5t8/griJu7JmCZq2mrVTjo0dXP6MJ8KNP
          K8f206ir/FPEUvWlNQ+qZCtTAYl+cn5J47EJOLkP6+eeWidCWRsHktzgllf+bTvqCGBsr
          nEuLzVMfdTUcIWjuo950wTfrTlb2u+3RQG21I2sI9pU9j2uebtig+Gy0U+adIlIrbd1yG
          8Wp1EOs7lAB1QIokAUa2fsvr+j0I3wQ+RLPyeBZ2lJ5J6Jsq3DVWBH5d6A68VxO5n5mM4
          oV0y+bRYGlmmAYwC9ufNcKILMM5l1pSpuaP4SquPKvqjWVwpKKPatR3uayBSzVtMvvAF2
          Vn3tPmhDD64VQGp5zmjDDRmzQlovSabm5zJMDGWcyPX4KcDMtpjohzBj3KnwdptrswHF3
          ZqcmpuqfZ5zkLnxGKNdGGdb4LocXwwv48/Ia0goyHBmm36hxH//Rzd7bD2e9hE=
