{{- $top := . -}}
{{- range $node, $cstates := .Values.cstatesProfile }}
---
apiVersion: power.intel.com/v1
kind: CStates
metadata:
  name: {{ $node }}
  namespace: intel-power
spec:
  {{- toYaml $cstates | nindent 2 }}
{{- end -}}
