# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: intel-power
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: intel-power-operator
      terminationGracePeriodSeconds: 10

      containers:
      - name: manager
        imagePullPolicy: IfNotPresent
        image: {{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}

        command:
        - /manager

        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop: ["ALL"]
 
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 0
            memory: 20Mi
 
        volumeMounts:
        - mountPath: /sys/fs
          name: cgroup
          mountPropagation: HostToContainer
          readOnly: false
        - mountPath: /power-manifests/power-node-agent-ds.yaml
          name: power-node-agent-ds
          subPath: power-node-agent-ds.yaml
          readOnly: true

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: Exists
          - weight: 1
            preference:
              matchExpressions:
              - key: "node-role.kubernetes.io/control-plane"
                operator: Exists

{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 6 }}
{{- end }}

      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

      volumes:
      - name: cgroup
        hostPath:
          path: /sys/fs
      - name: power-node-agent-ds
        configMap:
          name: power-node-agent-ds
