{{- $top := . -}}
{{- range $node, $powerworkload := .Values.sharedProfile }}
---
apiVersion: power.intel.com/v1
kind: PowerWorkload
metadata:
  name: shared-{{ $node }}-workload
  namespace: intel-power
spec:
  name: shared-{{ $node }}-workload
  allCores: true
  powerNodeSelector:
    kubernetes.io/hostname: {{ $node }}
  powerProfile: shared-{{ $node }}
  reservedCPUs:
  {{- range $powerworkload.reservedCPUs }}
  - {{. | int }}
  {{- end }}
{{- end -}}
