#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

HELM_APP_KUBERNETES_POWER_MANAGER = 'kubernetes-power-manager'
HELM_RELEASE_KUBERNETES_POWER_MANAGER = 'kubernetes-power-manager'
HELM_CHART_KUBERNETES_POWER_MANAGER = 'kubernetes-power-manager'
HELM_NS_KUBERNETES_POWER_MANAGER = 'intel-power'
HELM_APP_KUBERNETES_POWER_MANAGER_AGENT = 'power-node-agent'

HELM_APP_KUBERNETES_POWER_MANAGER_CRD_CSTATES = 'cstates.power.intel.com'
HELM_APP_KUBERNETES_POWER_MANAGER_CRD_POWERCONFIGS = 'powerconfigs.power.intel.com'
HELM_APP_KUBERNETES_POWER_MANAGER_CRD_POWERNODES = 'powernodes.power.intel.com'
HELM_APP_KUBERNETES_POWER_MANAGER_CRD_POWERPODS = 'powerpods.power.intel.com'
HELM_APP_KUBERNETES_POWER_MANAGER_CRD_POWERPROFILES = 'powerprofiles.power.intel.com'
HELM_APP_KUBERNETES_POWER_MANAGER_CRD_POWERWORKLOADS = 'powerworkloads.power.intel.com'
HELM_APP_KUBERNETES_POWER_MANAGER_CRD_TIMEOFDAYCRONJOBS = 'timeofdaycronjobs.power.intel.com'
HELM_APP_KUBERNETES_POWER_MANAGER_CRD_TIMEOFDAYS = 'timeofdays.power.intel.com'
HELM_APP_KUBERNETES_POWER_MANAGER_CRD_UNCORES = 'uncores.power.intel.com'

HELM_APP_KUBERNETES_POWER_MANAGER_CRDS = [
    HELM_APP_KUBERNETES_POWER_MANAGER_CRD_CSTATES,
    HELM_APP_KUBERNETES_POWER_MANAGER_CRD_POWERCONFIGS,
    HELM_APP_KUBERNETES_POWER_MANAGER_CRD_POWERNODES,
    HELM_APP_KUBERNETES_POWER_MANAGER_CRD_POWERPODS,
    HELM_APP_KUBERNETES_POWER_MANAGER_CRD_POWERPROFILES,
    HELM_APP_KUBERNETES_POWER_MANAGER_CRD_POWERWORKLOADS,
    HELM_APP_KUBERNETES_POWER_MANAGER_CRD_TIMEOFDAYCRONJOBS,
    HELM_APP_KUBERNETES_POWER_MANAGER_CRD_TIMEOFDAYS,
    HELM_APP_KUBERNETES_POWER_MANAGER_CRD_UNCORES
]

HELM_COMPONENT_LABEL = 'app.starlingx.io/component'
HELM_NFD_REQUIRED_PARAM = 'nfd-required'

# These parameters refer to the Node Feature Discovery (NFD) application.
# They should be kept in sync.
# https://opendev.org/starlingx/app-node-feature-discovery.
HELM_APP_NFD = 'node-feature-discovery'
HELM_NS_NFD = 'node-feature-discovery'
HELM_CHART_NFD = 'node-feature-discovery'

APPLICATION_CSTATE = "C1"
CSTATE_C0 = "POLL"
PLATFORM_CSTATE = "C6"
