[metadata]
name = k8sapp-kubernetes-power-manager
summary = StarlingX sysinv extensions for Kubernetes Power Manager
long_description = file: README.rst
long_description_content_type = text/x-rst
license = Apache 2.0
author = StarlingX
author_email = starlingx-discuss@lists.starlingx.io
url = https://www.starlingx.io/
classifiers =
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9

[files]
packages =
    k8sapp_kubernetes_power_manager

[global]
setup-hooks =
    pbr.hooks.setup_hook

[entry_points]
systemconfig.helm_applications =
    kubernetes-power-manager = systemconfig.helm_plugins.kubernetes_power_manager

systemconfig.app_lifecycle =
    kubernetes-power-manager = k8sapp_kubernetes_power_manager.lifecycle.lifecycle_kubernetes_power_manager:KubernetesPowerManagerAppLifecycleOperator

systemconfig.helm_plugins.kubernetes_power_manager =
    001_kubernetes-power-manager = k8sapp_kubernetes_power_manager.helm.kubernetes_power_manager:KubernetesPowerManagerHelm

[bdist_wheel]
universal = 1
